create table "public"."bounties" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "deleted_at" timestamp without time zone,
    "title" text not null,
    "points" bigint not null,
    "completed" boolean not null default false,
    "id" uuid not null
);


alter table "public"."bounties" enable row level security;

create table "public"."bounties_join_table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid,
    "bounty_id" uuid
);


alter table "public"."bounties_join_table" enable row level security;

create table "public"."data_points" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "deleted_at" timestamp without time zone,
    "points" bigint not null default '0'::bigint,
    "id" uuid not null,
    "child_id" uuid not null
);


alter table "public"."data_points" enable row level security;

create table "public"."user_profile" (
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "deleted_at" timestamp without time zone,
    "userName" text,
    "type" text default 'parent'::text,
    "points" bigint default '0'::bigint,
    "negativePoints" bigint default '0'::bigint,
    "id" uuid not null,
    "parent_id" uuid not null
);


alter table "public"."user_profile" enable row level security;

CREATE UNIQUE INDEX bountie_join_table_pkey ON public.bounties_join_table USING btree (id);

CREATE UNIQUE INDEX bounties_pkey ON public.bounties USING btree (id);

CREATE UNIQUE INDEX data_points_pkey ON public.data_points USING btree (id);

CREATE UNIQUE INDEX user_profile_pkey ON public.user_profile USING btree (id);

alter table "public"."bounties" add constraint "bounties_pkey" PRIMARY KEY using index "bounties_pkey";

alter table "public"."bounties_join_table" add constraint "bountie_join_table_pkey" PRIMARY KEY using index "bountie_join_table_pkey";

alter table "public"."data_points" add constraint "data_points_pkey" PRIMARY KEY using index "data_points_pkey";

alter table "public"."user_profile" add constraint "user_profile_pkey" PRIMARY KEY using index "user_profile_pkey";

alter table "public"."bounties_join_table" add constraint "bountie_join_table_bounty_id_fkey" FOREIGN KEY (bounty_id) REFERENCES bounties(id) not valid;

alter table "public"."bounties_join_table" validate constraint "bountie_join_table_bounty_id_fkey";

alter table "public"."bounties_join_table" add constraint "bountie_join_table_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profile(id) not valid;

alter table "public"."bounties_join_table" validate constraint "bountie_join_table_user_id_fkey";

alter table "public"."data_points" add constraint "data_points_child_id_fkey" FOREIGN KEY (child_id) REFERENCES user_profile(id) ON UPDATE CASCADE not valid;

alter table "public"."data_points" validate constraint "data_points_child_id_fkey";

alter table "public"."user_profile" add constraint "user_profile_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES user_profile(id) ON UPDATE CASCADE not valid;

alter table "public"."user_profile" validate constraint "user_profile_parent_id_fkey";

grant delete on table "public"."bounties" to "anon";

grant insert on table "public"."bounties" to "anon";

grant references on table "public"."bounties" to "anon";

grant select on table "public"."bounties" to "anon";

grant trigger on table "public"."bounties" to "anon";

grant truncate on table "public"."bounties" to "anon";

grant update on table "public"."bounties" to "anon";

grant delete on table "public"."bounties" to "authenticated";

grant insert on table "public"."bounties" to "authenticated";

grant references on table "public"."bounties" to "authenticated";

grant select on table "public"."bounties" to "authenticated";

grant trigger on table "public"."bounties" to "authenticated";

grant truncate on table "public"."bounties" to "authenticated";

grant update on table "public"."bounties" to "authenticated";

grant delete on table "public"."bounties" to "service_role";

grant insert on table "public"."bounties" to "service_role";

grant references on table "public"."bounties" to "service_role";

grant select on table "public"."bounties" to "service_role";

grant trigger on table "public"."bounties" to "service_role";

grant truncate on table "public"."bounties" to "service_role";

grant update on table "public"."bounties" to "service_role";

grant delete on table "public"."bounties_join_table" to "anon";

grant insert on table "public"."bounties_join_table" to "anon";

grant references on table "public"."bounties_join_table" to "anon";

grant select on table "public"."bounties_join_table" to "anon";

grant trigger on table "public"."bounties_join_table" to "anon";

grant truncate on table "public"."bounties_join_table" to "anon";

grant update on table "public"."bounties_join_table" to "anon";

grant delete on table "public"."bounties_join_table" to "authenticated";

grant insert on table "public"."bounties_join_table" to "authenticated";

grant references on table "public"."bounties_join_table" to "authenticated";

grant select on table "public"."bounties_join_table" to "authenticated";

grant trigger on table "public"."bounties_join_table" to "authenticated";

grant truncate on table "public"."bounties_join_table" to "authenticated";

grant update on table "public"."bounties_join_table" to "authenticated";

grant delete on table "public"."bounties_join_table" to "service_role";

grant insert on table "public"."bounties_join_table" to "service_role";

grant references on table "public"."bounties_join_table" to "service_role";

grant select on table "public"."bounties_join_table" to "service_role";

grant trigger on table "public"."bounties_join_table" to "service_role";

grant truncate on table "public"."bounties_join_table" to "service_role";

grant update on table "public"."bounties_join_table" to "service_role";

grant delete on table "public"."data_points" to "anon";

grant insert on table "public"."data_points" to "anon";

grant references on table "public"."data_points" to "anon";

grant select on table "public"."data_points" to "anon";

grant trigger on table "public"."data_points" to "anon";

grant truncate on table "public"."data_points" to "anon";

grant update on table "public"."data_points" to "anon";

grant delete on table "public"."data_points" to "authenticated";

grant insert on table "public"."data_points" to "authenticated";

grant references on table "public"."data_points" to "authenticated";

grant select on table "public"."data_points" to "authenticated";

grant trigger on table "public"."data_points" to "authenticated";

grant truncate on table "public"."data_points" to "authenticated";

grant update on table "public"."data_points" to "authenticated";

grant delete on table "public"."data_points" to "service_role";

grant insert on table "public"."data_points" to "service_role";

grant references on table "public"."data_points" to "service_role";

grant select on table "public"."data_points" to "service_role";

grant trigger on table "public"."data_points" to "service_role";

grant truncate on table "public"."data_points" to "service_role";

grant update on table "public"."data_points" to "service_role";

grant delete on table "public"."user_profile" to "anon";

grant insert on table "public"."user_profile" to "anon";

grant references on table "public"."user_profile" to "anon";

grant select on table "public"."user_profile" to "anon";

grant trigger on table "public"."user_profile" to "anon";

grant truncate on table "public"."user_profile" to "anon";

grant update on table "public"."user_profile" to "anon";

grant delete on table "public"."user_profile" to "authenticated";

grant insert on table "public"."user_profile" to "authenticated";

grant references on table "public"."user_profile" to "authenticated";

grant select on table "public"."user_profile" to "authenticated";

grant trigger on table "public"."user_profile" to "authenticated";

grant truncate on table "public"."user_profile" to "authenticated";

grant update on table "public"."user_profile" to "authenticated";

grant delete on table "public"."user_profile" to "service_role";

grant insert on table "public"."user_profile" to "service_role";

grant references on table "public"."user_profile" to "service_role";

grant select on table "public"."user_profile" to "service_role";

grant trigger on table "public"."user_profile" to "service_role";

grant truncate on table "public"."user_profile" to "service_role";

grant update on table "public"."user_profile" to "service_role";


